buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'jacoco'
    id 'com.diffplug.spotless' version '7.2.1'
    id 'org.wiremock.tools.gradle.wiremock-extension-convention' version '0.5.1'
}

group 'org.wiremock.extensions'
project.ext {
    versions = [
            caffeine  : '3.2.4',
            handlebars: '4.5.1',
            wiremock  : '3.13.2'
    ]
}

dependencies {
    compileOnly("org.wiremock:wiremock:${versions.wiremock}")
    implementation("com.github.ben-manes.caffeine:caffeine:${versions.caffeine}")
    implementation("com.github.jknack:handlebars-helpers:${versions.handlebars}") {
        exclude group: 'org.mozilla', module: 'rhino'
    }
    testImplementation("org.wiremock:wiremock:${versions.wiremock}")
}

java {
    sourceCompatibility = 11
    targetCompatibility = 11
}

shadowJar {
    relocate "com.github.ben-manes.caffeine", 'wiremock.com.github.ben-manes.caffeine'
    relocate "com.github.jknack", 'wiremock.com.github.jknack'
}

test {
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        csv.required = true
        html.required = true
    }
}
